<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>OpenDictate.Prototype</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OpenDictate.Core/OpenDictate.Core.csproj" />
    <ProjectReference Include="../OpenDictate.Windows/OpenDictate.Windows.csproj" />
    <PackageReference Include="NAudio.Wasapi" Version="3.1.0" />
  </ItemGroup>
</Project>
