version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directory: /linux
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
    open-pull-requests-limit: 3
    groups:
      rust:
        patterns:
          - '*'

  - package-ecosystem: nuget
    directory: /windows
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
    open-pull-requests-limit: 3
    groups:
      nuget:
        patterns:
          - '*'
